// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1qiGoSKjM7uKKRG6dsW6-jkM5IX8o6Ok',
    appId: '1:625342909849:web:909b8ed53a1e507a3a1708',
    messagingSenderId: '625342909849',
    projectId: 'smart-helmet-app-a0c13',
    authDomain: 'smart-helmet-app-a0c13.firebaseapp.com',
    storageBucket: 'smart-helmet-app-a0c13.firebasestorage.app',
    measurementId: 'G-ELKY7DBDT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSd2VX1ODPFsxwgkdi__AJPxr3V4vojdY',
    appId: '1:625342909849:android:7afab728858dd7bd3a1708',
    messagingSenderId: '625342909849',
    projectId: 'smart-helmet-app-a0c13',
    storageBucket: 'smart-helmet-app-a0c13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3EIxx0zJJivW7-uB7fNen3QY1q6aUpus',
    appId: '1:625342909849:ios:0ea73a92bfb30e393a1708',
    messagingSenderId: '625342909849',
    projectId: 'smart-helmet-app-a0c13',
    storageBucket: 'smart-helmet-app-a0c13.firebasestorage.app',
    iosBundleId: 'com.example.smartHelmetV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1qiGoSKjM7uKKRG6dsW6-jkM5IX8o6Ok',
    appId: '1:625342909849:web:9e03d444a4d10e403a1708',
    messagingSenderId: '625342909849',
    projectId: 'smart-helmet-app-a0c13',
    authDomain: 'smart-helmet-app-a0c13.firebaseapp.com',
    storageBucket: 'smart-helmet-app-a0c13.firebasestorage.app',
    measurementId: 'G-PKBYRHKVCS',
  );
}
